<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Student;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class StudentSeederX extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            // ================== KELAS XA (dari E1.html) ==================
            ['nis' => '5921', 'name' => 'AFIK OKTA FIAN', 'class' => 'XA'],
            ['nis' => '5953', 'name' => 'AKHIF IKHSAN MUZAKI', 'class' => 'XA'],
            ['nis' => '5972', 'name' => 'ALIF ALBAITAMA PUTRA', 'class' => 'XA'],
            ['nis' => '5983', 'name' => 'ALIIFA PUSPITANINGRUM', 'class' => 'XA'],
            ['nis' => '5987', 'name' => 'ALINGKA BULAN RAMADHANI', 'class' => 'XA'],
            ['nis' => '6045', 'name' => 'ATHAULLAH DAIB PRATAMA', 'class' => 'XA'],
            ['nis' => '6108', 'name' => 'AZALEA DIVANA CALISTA SANDRI', 'class' => 'XA'],
            ['nis' => '6116', 'name' => 'BIMANA INDRA JAYAMRATA', 'class' => 'XA'],
            ['nis' => '5941', 'name' => 'DIVA DWI SAPUTRI', 'class' => 'XA'],
            ['nis' => '5958', 'name' => 'FAHRI EKO SUPRIYATNO', 'class' => 'XA'],
            ['nis' => '5976', 'name' => 'FAVIAN RAMIRO NAZHIR', 'class' => 'XA'],
            ['nis' => '5978', 'name' => 'FAYZA ARFAN ZAIN', 'class' => 'XA'],
            ['nis' => '5982', 'name' => 'FIRANA MEYLIA ZAHRANI', 'class' => 'XA'],
            ['nis' => '5992', 'name' => 'GANENDRA JORELL ISLAM', 'class' => 'XA'],
            ['nis' => '5993', 'name' => 'GELEN ABIE IBRAHIM', 'class' => 'XA'],
            ['nis' => '6004', 'name' => 'HISYAM ABQORI GUSTANTA', 'class' => 'XA'],
            ['nis' => '6005', 'name' => 'HYANG DAMARU LANGIT', 'class' => 'XA'],
            ['nis' => '6015', 'name' => 'INTAN OCTAVIOLA NINGRUM', 'class' => 'XA'],
            ['nis' => '6018', 'name' => 'ISA NATA LENI', 'class' => 'XA'],
            ['nis' => '6028', 'name' => 'KEVIN ADITYA PUTRA PRAPTAMA', 'class' => 'XA'],
            ['nis' => '6036', 'name' => 'LASKAR SUDIRMAN', 'class' => 'XA'],
            ['nis' => '6049', 'name' => 'LISTIARA WIDHIANINGRUM', 'class' => 'XA'],
            ['nis' => '6053', 'name' => 'LUTFI HAKIM', 'class' => 'XA'],
            ['nis' => '6064', 'name' => 'MAHARJUNA SATYA HAPRABU', 'class' => 'XA'],
            ['nis' => '6085', 'name' => 'NAJMI ATHWI FATHIN', 'class' => 'XA'],
            ['nis' => '6130', 'name' => 'RAKA HAFIZ PRADANA', 'class' => 'XA'],
            ['nis' => '6137', 'name' => 'RAYHAN AMIINUDIN ASYROF', 'class' => 'XA'],
            ['nis' => '6138', 'name' => 'RAYMOND DENNIS FERNANDA', 'class' => 'XA'],
            ['nis' => '6048', 'name' => 'SANTA FELLIA PARAMESWARI', 'class' => 'XA'],
            ['nis' => '5926', 'name' => 'SATRIYO GALIH PRIAMBODO PAMUNGKAS', 'class' => 'XA'],
            ['nis' => '5935', 'name' => 'SHIDDIQ KURNIAWAN ZUHAIR', 'class' => 'XA'],
            ['nis' => '6032', 'name' => 'VACYA HOLLY LATIFA', 'class' => 'XA'],
            ['nis' => '6037', 'name' => 'VARO RAHA DEWA NATA', 'class' => 'XA'],
            ['nis' => '6058', 'name' => 'WISNU GALANG PRADITA', 'class' => 'XA'],
            ['nis' => '6131', 'name' => 'YUAN MAHARANI', 'class' => 'XA'],
            ['nis' => '6145', 'name' => 'ZAKI DELLA MUSTAQIM', 'class' => 'XA'],

            // ================== KELAS XB (dari E2.html) ==================
            ['nis' => '5914', 'name' => 'ABIYYU MU\'AFA ATMAJA', 'class' => 'XB'],
            ['nis' => '5930', 'name' => 'AGMIFAN HERNI ELITA', 'class' => 'XB'],
            ['nis' => '5947', 'name' => 'AKBAR RIZKI SYAUQI', 'class' => 'XB'],
            ['nis' => '5969', 'name' => 'ALBERTUS MAGNUS ISWARA BEKTI MURTIANDARU', 'class' => 'XB'],
            ['nis' => '5977', 'name' => 'ALIFAH HELMANIA NUGROHO', 'class' => 'XB'],
            ['nis' => '6026', 'name' => 'ANNAYA ARSYABELA RAHMADANTI', 'class' => 'XB'],
            ['nis' => '6060', 'name' => 'AUFAA ANDHADHARI HING RAHINA ARANE', 'class' => 'XB'],
            ['nis' => '6062', 'name' => 'AULIA NOVIANDARI', 'class' => 'XB'],
            ['nis' => '6086', 'name' => 'AURA NAFISAH', 'class' => 'XB'],
            ['nis' => '6090', 'name' => 'AVICIENA RIZKY RAHMANDIEN', 'class' => 'XB'],
            ['nis' => '6111', 'name' => 'AZZAHRA CHOIRUNISSA', 'class' => 'XB'],
            ['nis' => '5924', 'name' => 'DASA OKTAF SHAFAYADIAN', 'class' => 'XB'],
            ['nis' => '5925', 'name' => 'DAVIN CAHYA NUGROHO', 'class' => 'XB'],
            ['nis' => '5928', 'name' => 'DEARA SAFA PUTRI AULIA', 'class' => 'XB'],
            ['nis' => '5960', 'name' => 'FAIZ ANINDRA PUTRA', 'class' => 'XB'],
            ['nis' => '5973', 'name' => 'FAUZI REIHANANTO PUTRA WAHYUDI', 'class' => 'XB'],
            ['nis' => '5974', 'name' => 'FAUZI WIRA BACHTIAR', 'class' => 'XB'],
            ['nis' => '5997', 'name' => 'GREGORIUS GADHANG ARYA SANCOKO', 'class' => 'XB'],
            ['nis' => '5998', 'name' => 'HANAN HABIB HIBRIZI', 'class' => 'XB'],
            ['nis' => '6003', 'name' => 'HINDUN', 'class' => 'XB'],
            ['nis' => '6008', 'name' => 'ICHA NOUVAL INDRIANI', 'class' => 'XB'],
            ['nis' => '6059', 'name' => 'MAHANDENA NERISSA FIRDAUS', 'class' => 'XB'],
            ['nis' => '6066', 'name' => 'MARIA YOURVENA VITA OLIVIA', 'class' => 'XB'],
            ['nis' => '6071', 'name' => 'MONIKA STELLA ANA MARDI', 'class' => 'XB'],
            ['nis' => '6072', 'name' => 'MUHAMMAD HABIB LUTHFI', 'class' => 'XB'],
            ['nis' => '6081', 'name' => 'NADIA WIRASTUTI', 'class' => 'XB'],
            ['nis' => '6107', 'name' => 'NUR IHSAN NUGRAHAJATI', 'class' => 'XB'],
            ['nis' => '6115', 'name' => 'ORLYN AURIAN NIKAYA', 'class' => 'XB'],
            ['nis' => '6120', 'name' => 'PETRA PANJER RINO', 'class' => 'XB'],
            ['nis' => '6122', 'name' => 'PUTRI ARVA KIRANA', 'class' => 'XB'],
            ['nis' => '6153', 'name' => 'SAFINA YULINAGUS SAKHA\'U', 'class' => 'XB'],
            ['nis' => '6156', 'name' => 'SALSABILLA ANGEL SETIANA', 'class' => 'XB'],
            ['nis' => '6114', 'name' => 'SATRIA AFSHONNATA', 'class' => 'XB'],
            ['nis' => '5965', 'name' => 'STEEVANUS ARIENO SETIAWAN', 'class' => 'XB'],
            ['nis' => '6001', 'name' => 'SYAFIRA HARUMI PUTRI', 'class' => 'XB'],
            ['nis' => '6021', 'name' => 'UGRASENA ARSYADAN NUGROHO', 'class' => 'XB'],

            // ================== KELAS XC (dari E3.html) ==================
            ['nis' => '5952', 'name' => 'AKHDAN IS\'AF PAMUNGKAS', 'class' => 'XC'],
            ['nis' => '5981', 'name' => 'ALIFAH KHANSA KHAIRUNNISA', 'class' => 'XC'],
            ['nis' => '6040', 'name' => 'ARIQ KHOIRUN ZAIN', 'class' => 'XC'],
            ['nis' => '6054', 'name' => 'AUFA SYAFI PUTRA BUDI', 'class' => 'XC'],
            ['nis' => '6093', 'name' => 'AVRILLIANO EKA SAPUTRA', 'class' => 'XC'],
            ['nis' => '6095', 'name' => 'AVRITA RAISACHATTRA PUTRI ARDYA', 'class' => 'XC'],
            ['nis' => '6161', 'name' => 'CORNELIUS DAVU AXELLY GALENO', 'class' => 'XC'],
            ['nis' => '5929', 'name' => 'DERISTA NACHA RAMADHANI', 'class' => 'XC'],
            ['nis' => '5939', 'name' => 'DITA AMELIA PUTRI', 'class' => 'XC'],
            ['nis' => '5940', 'name' => 'DITA INDRIYANI', 'class' => 'XC'],
            ['nis' => '5943', 'name' => 'ELISABETH CRISTABEL NYACITA MEDARI', 'class' => 'XC'],
            ['nis' => '5946', 'name' => 'ELVINA NOVA ELISYA', 'class' => 'XC'],
            ['nis' => '5957', 'name' => 'FADHLAN DZAKIY SULHAN', 'class' => 'XC'],
            ['nis' => '5986', 'name' => 'GAIZEKA FERO ALQUINO', 'class' => 'XC'],
            ['nis' => '5996', 'name' => 'GREGORIUS ABDI RAHMANTO', 'class' => 'XC'],
            ['nis' => '6002', 'name' => 'HANIFAH DHIYA ROHMANI', 'class' => 'XC'],
            ['nis' => '6024', 'name' => 'JESSICA HANNA AVRILLIYA', 'class' => 'XC'],
            ['nis' => '6067', 'name' => 'MASYAYU NUR CAHYANI', 'class' => 'XC'],
            ['nis' => '6069', 'name' => 'MIFTHAKHUL HANAN VIRGANI', 'class' => 'XC'],
            ['nis' => '6078', 'name' => 'MUHAMMAD ZAFIF FADZLAN AL BANI', 'class' => 'XC'],
            ['nis' => '6083', 'name' => 'NAILA MUAZARA ULFA VANIA', 'class' => 'XC'],
            ['nis' => '6102', 'name' => 'NI\'MATUSSA\'ADAH', 'class' => 'XC'],
            ['nis' => '6112', 'name' => 'OKTAVIA INGGRIT ANGGRAENI', 'class' => 'XC'],
            ['nis' => '6125', 'name' => 'RAFALIA ADETYA IVANY', 'class' => 'XC'],
            ['nis' => '6135', 'name' => 'RANIENTA HAPPY AULIA', 'class' => 'XC'],
            ['nis' => '6139', 'name' => 'REYHANA ELFA FAURIZA', 'class' => 'XC'],
            ['nis' => '6148', 'name' => 'RIZKITA HANNA PRASTYANI PUTRI', 'class' => 'XC'],
            ['nis' => '6154', 'name' => 'SALMAN AL FARISI NUR AHSAN', 'class' => 'XC'],
            ['nis' => '5951', 'name' => 'SHINTA NUR ARASI', 'class' => 'XC'],
            ['nis' => '6031', 'name' => 'UMAR', 'class' => 'XC'],
            ['nis' => '6035', 'name' => 'VALENCIA KRISANTA PRASETIYO', 'class' => 'XC'],
            ['nis' => '6043', 'name' => 'VERENA JESSI ELVINA', 'class' => 'XC'],
            ['nis' => '6047', 'name' => 'VINCENTIUS FIEGO AUGUSTHA PRADIPTHA', 'class' => 'XC'],
            ['nis' => '6052', 'name' => 'WILDAN FAIQ ARKANA', 'class' => 'XC'],
            ['nis' => '6077', 'name' => 'WRESNIWIRA IRSYADIN NUGROHO', 'class' => 'XC'],
            ['nis' => '6124', 'name' => 'YOGA PRATAMA PUTRA SETIAWAN', 'class' => 'XC'],

            // ================== KELAS XD (dari E4.html) ==================
            ['nis' => '5919', 'name' => 'ADHYASTA HANIF PRAMANA', 'class' => 'XD'],
            ['nis' => '5936', 'name' => 'AISYAH', 'class' => 'XD'],
            ['nis' => '5964', 'name' => 'AL FIRLI SETIANINGSIH', 'class' => 'XD'],
            ['nis' => '5970', 'name' => 'ALESHA SHILO GRACEANNE', 'class' => 'XD'],
            ['nis' => '5988', 'name' => 'ALVIANA MERY LISTIYANTI', 'class' => 'XD'],
            ['nis' => '6009', 'name' => 'ANANDA TIARA SALSABILA', 'class' => 'XD'],
            ['nis' => '6039', 'name' => 'ARIF NURHIDAYAT', 'class' => 'XD'],
            ['nis' => '6044', 'name' => 'ASHIFA KEYLA RAMADHANI', 'class' => 'XD'],
            ['nis' => '6074', 'name' => 'AURA AZARIA LAKSITA NARISWARI', 'class' => 'XD'],
            ['nis' => '6088', 'name' => 'AURA SYIFA AMIRA', 'class' => 'XD'],
            ['nis' => '6136', 'name' => 'CESTARIO SATRIA YUKO', 'class' => 'XD'],
            ['nis' => '6140', 'name' => 'CHANTIKA SARI', 'class' => 'XD'],
            ['nis' => '6160', 'name' => 'CLARA FEBRIANA LARASSATI', 'class' => 'XD'],
            ['nis' => '5944', 'name' => 'ELSA FANUKE DIAH LESTARI', 'class' => 'XD'],
            ['nis' => '5955', 'name' => 'EUNIQUE CHRISTABEL AMALIA', 'class' => 'XD'],
            ['nis' => '5975', 'name' => 'FAUZIA SALSABILA', 'class' => 'XD'],
            ['nis' => '5989', 'name' => 'GALANG AZKA MAULANA SATRIANI', 'class' => 'XD'],
            ['nis' => '6000', 'name' => 'HANIF ATHALLA PUTRA ISANDI', 'class' => 'XD'],
            ['nis' => '6019', 'name' => 'ISMA WATI', 'class' => 'XD'],
            ['nis' => '6022', 'name' => 'JALER RYAN SETYAJI', 'class' => 'XD'],
            ['nis' => '6029', 'name' => 'KHALILLAH ZAHRA NURJANAH', 'class' => 'XD'],
            ['nis' => '6042', 'name' => 'LASYA ABDULLAH NAJIIB', 'class' => 'XD'],
            ['nis' => '6046', 'name' => 'LATHIFAH AJENG KUSUMASTUTI', 'class' => 'XD'],
            ['nis' => '6063', 'name' => 'MAHARANI TALITHA RAMADHANI', 'class' => 'XD'],
            ['nis' => '6065', 'name' => 'MALIK AKBAR SAKHIY', 'class' => 'XD'],
            ['nis' => '6073', 'name' => 'MUHAMMAD IKHSAN', 'class' => 'XD'],
            ['nis' => '6091', 'name' => 'NATHALIA ROSA WULANDARI', 'class' => 'XD'],
            ['nis' => '6098', 'name' => 'NAYLA NUR IZZATI', 'class' => 'XD'],
            ['nis' => '6099', 'name' => 'NESYA RANIA ANANTA', 'class' => 'XD'],
            ['nis' => '6113', 'name' => 'OLIVIA REYSYAFA', 'class' => 'XD'],
            ['nis' => '6117', 'name' => 'PANCAR DAMAI ADVENTA', 'class' => 'XD'],
            ['nis' => '6141', 'name' => 'REYNANSYAH DWI PAMUNGKAS', 'class' => 'XD'],
            ['nis' => '6144', 'name' => 'RIANA AZARIA RAMADHANI', 'class' => 'XD'],
            ['nis' => '6149', 'name' => 'RIZKY RIDHO RAMADHAN', 'class' => 'XD'],
            ['nis' => '6151', 'name' => 'RYUJI GEMILANG JALU UTOMO', 'class' => 'XD'],
            ['nis' => '6110', 'name' => 'YEHEZKIEL SERAFINO', 'class' => 'XD'],

            // ================== KELAS XE (dari E5.html) ==================
            ['nis' => '5920', 'name' => 'ADRIAN ADAM MAHARDIKA', 'class' => 'XE'],
            ['nis' => '5971', 'name' => 'AL-FATIH AZKA PUTRA', 'class' => 'XE'],
            ['nis' => '5990', 'name' => 'AM ALWAN ALHUWAIDI', 'class' => 'XE'],
            ['nis' => '6006', 'name' => 'AMELIA NUR AZIZAH', 'class' => 'XE'],
            ['nis' => '6007', 'name' => 'ANANDA DAFAZE NAFEZANIKO', 'class' => 'XE'],
            ['nis' => '6030', 'name' => 'APRELIA YAFI ZAHIDAH', 'class' => 'XE'],
            ['nis' => '6119', 'name' => 'CAESARO MANIHURUK', 'class' => 'XE'],
            ['nis' => '6132', 'name' => 'CANDRA BIMA PAMUNGKAS', 'class' => 'XE'],
            ['nis' => '6152', 'name' => 'CHARLYTA ADRINI PUTRI SHOLEHAH', 'class' => 'XE'],
            ['nis' => '6158', 'name' => 'CHINTIYA MEISAJAYA', 'class' => 'XE'],
            ['nis' => '5918', 'name' => 'DAFI NURHUDA', 'class' => 'XE'],
            ['nis' => '5923', 'name' => 'DANENDRA BINTANG RAMADHAN', 'class' => 'XE'],
            ['nis' => '5937', 'name' => 'DIAN DWI PUSPITA', 'class' => 'XE'],
            ['nis' => '5938', 'name' => 'DIKA ARIFIN SAPUTRA', 'class' => 'XE'],
            ['nis' => '5950', 'name' => 'ERLIANA PUTRI ADI WINATA', 'class' => 'XE'],
            ['nis' => '5956', 'name' => 'EZIO RAZQA ABRISAM', 'class' => 'XE'],
            ['nis' => '5962', 'name' => 'FAJRILLAH AZZAM', 'class' => 'XE'],
            ['nis' => '5966', 'name' => 'FARISA MUTIA AZZAHRA', 'class' => 'XE'],
            ['nis' => '5980', 'name' => 'FEBYANA NUR UTAMI', 'class' => 'XE'],
            ['nis' => '5984', 'name' => 'FITRIA LATIFA', 'class' => 'XE'],
            ['nis' => '5995', 'name' => 'GREESTIYA JAVELINA LISTY', 'class' => 'XE'],
            ['nis' => '5999', 'name' => 'HANIDA ZULFA NUR AINI', 'class' => 'XE'],
            ['nis' => '6017', 'name' => 'IRZA ALMER ZAKY', 'class' => 'XE'],
            ['nis' => '6068', 'name' => 'MAYSAHWA AFNAITA', 'class' => 'XE'],
            ['nis' => '6075', 'name' => 'MUHAMMAD PANDU WICAKSONO', 'class' => 'XE'],
            ['nis' => '6084', 'name' => 'NAJLA RAISYA ATHAYA', 'class' => 'XE'],
            ['nis' => '6104', 'name' => 'NISRINA RIFDA SALMA PUTRI', 'class' => 'XE'],
            ['nis' => '6105', 'name' => 'NOVITA AYU LESTARI', 'class' => 'XE'],
            ['nis' => '6133', 'name' => 'RAKESYA NOVIANA', 'class' => 'XE'],
            ['nis' => '6147', 'name' => 'RIZKA NURUL AINI', 'class' => 'XE'],
            ['nis' => '5917', 'name' => 'SATRIA YUDHATAMA PANALATAS', 'class' => 'XE'],
            ['nis' => '6012', 'name' => 'SYAVIRA ZAHRA', 'class' => 'XE'],
            ['nis' => '6013', 'name' => 'SYAZA NAURA BILLAH', 'class' => 'XE'],
            ['nis' => '6050', 'name' => 'VIONA KALISTA MAHESWARI', 'class' => 'XE'],
            ['nis' => '6109', 'name' => 'YASFHIEN CHUMAERA', 'class' => 'XE'],
            ['nis' => '6150', 'name' => 'ZAMRI LAILLA FATMAWATI', 'class' => 'XE'],

            // ================== KELAS XF (dari E6.html) ==================
            ['nis' => '5915', 'name' => 'ABU NUFAIL', 'class' => 'XF'],
            ['nis' => '5942', 'name' => 'AISYAH FITRI RAMADHAN', 'class' => 'XF'],
            ['nis' => '6023', 'name' => 'ANGGENY SAFIRA AMBAR RAMADHANY', 'class' => 'XF'],
            ['nis' => '6103', 'name' => 'AZAHRA SYIFA AULIA', 'class' => 'XF'],
            ['nis' => '6155', 'name' => 'CHELSI ARUM SAFITRI', 'class' => 'XF'],
            ['nis' => '6162', 'name' => 'CYNTIA TRISTA NINGTYAS', 'class' => 'XF'],
            ['nis' => '5916', 'name' => 'DAFFA HAFISH ARYANKA', 'class' => 'XF'],
            ['nis' => '5922', 'name' => 'DAMIA AMALINA NURDINA', 'class' => 'XF'],
            ['nis' => '5932', 'name' => 'DESTA AFIRA INDRIYANA', 'class' => 'XF'],
            ['nis' => '5945', 'name' => 'ELSY RAHMA KHOIRUNNISA', 'class' => 'XF'],
            ['nis' => '5959', 'name' => 'FAHRIZA HAFIS PUTRA WIBAWA', 'class' => 'XF'],
            ['nis' => '5979', 'name' => 'FEBTRI LESNA SAWATI', 'class' => 'XF'],
            ['nis' => '6011', 'name' => 'INAS MARTIZA', 'class' => 'XF'],
            ['nis' => '6027', 'name' => 'KAYLA ANINDHINTA PURANIA', 'class' => 'XF'],
            ['nis' => '6051', 'name' => 'LIUZEUS TIMBASZ', 'class' => 'XF'],
            ['nis' => '6056', 'name' => 'LUTHFIYA FAATIN FADHILA', 'class' => 'XF'],
            ['nis' => '6057', 'name' => 'MAGHFIRA ALIF QURROTA A\'YUN', 'class' => 'XF'],
            ['nis' => '6079', 'name' => 'MUTIARA SHAFA AZZAHRA', 'class' => 'XF'],
            ['nis' => '6080', 'name' => 'NADIA MUKHBITA ZAHRAN', 'class' => 'XF'],
            ['nis' => '6087', 'name' => 'NARENDRA RYANDHI ARYASATYA NUGRAHA', 'class' => 'XF'],
            ['nis' => '6092', 'name' => 'NAUFAL DANISH ERNANDA', 'class' => 'XF'],
            ['nis' => '6097', 'name' => 'NAYAKA GHATFAN WIDYADANA', 'class' => 'XF'],
            ['nis' => '6121', 'name' => 'PUTRA GALIH AGUNG', 'class' => 'XF'],
            ['nis' => '6123', 'name' => 'RADO IKHTIAR JAILANI', 'class' => 'XF'],
            ['nis' => '6126', 'name' => 'RAFFI AHMAD', 'class' => 'XF'],
            ['nis' => '6127', 'name' => 'RAIHAN ADIRAJASA', 'class' => 'XF'],
            ['nis' => '6128', 'name' => 'RAISHA ALMA HIDAYAH', 'class' => 'XF'],
            ['nis' => '6142', 'name' => 'REYZA AHID ANSHORI', 'class' => 'XF'],
            ['nis' => '6146', 'name' => 'RIDHO ICHWANUDIN', 'class' => 'XF'],
            ['nis' => '6134', 'name' => 'SATRIA WAHYU SAMPURNA WIBAWA', 'class' => 'XF'],
            ['nis' => '5963', 'name' => 'SRI WARDANI PUTRI ALFARIZY', 'class' => 'XF'],
            ['nis' => '6020', 'name' => 'TSALSA BILLA JUWITA', 'class' => 'XF'],
            ['nis' => '6106', 'name' => 'YARISTIA PUSPA MURTI', 'class' => 'XF'],
            ['nis' => '6129', 'name' => 'YOGYA TULUS MUSTIKA ARUM', 'class' => 'XF'],
            ['nis' => '6157', 'name' => 'ZASKIA ASWA KHOIRUNNISA', 'class' => 'XF'],
            ['nis' => '6164', 'name' => 'ZIVANNA PUTRI PURWAJANNU', 'class' => 'XF'],

            // ================== KELAS XG (dari E7.html) ==================
            ['nis' => '5927', 'name' => 'AFNAN PUTRA ATSILA', 'class' => 'XG'],
            ['nis' => '5934', 'name' => 'AHMAD ITSNAN FATHUL AZZAM', 'class' => 'XG'],
            ['nis' => '5948', 'name' => 'AKBAR SETYAWAN', 'class' => 'XG'],
            ['nis' => '5985', 'name' => 'ALINA CAHYANI SEKAR TELASIH', 'class' => 'XG'],
            ['nis' => '6010', 'name' => 'ANASTASYA CORNELIA MELATI P J', 'class' => 'XG'],
            ['nis' => '6014', 'name' => 'ANASYA NURHAYATI', 'class' => 'XG'],
            ['nis' => '6038', 'name' => 'ARIAN PANJI HUTOMO', 'class' => 'XG'],
            ['nis' => '6041', 'name' => 'ARSYADRIANO NAVARA ISHA', 'class' => 'XG'],
            ['nis' => '6061', 'name' => 'AULIA ANASTASYA PUTRI DWI KINANTI', 'class' => 'XG'],
            ['nis' => '5913', 'name' => 'DAANIA IFZA PUTRI HERLINA', 'class' => 'XG'],
            ['nis' => '5933', 'name' => 'DEWA KURANTAKA NUR BUANA', 'class' => 'XG'],
            ['nis' => '5949', 'name' => 'ERICK NEVLAND', 'class' => 'XG'],
            ['nis' => '5961', 'name' => 'FAIZ NUR KHOLID', 'class' => 'XG'],
            ['nis' => '5967', 'name' => 'FASA SEPTI HANDAYANI', 'class' => 'XG'],
            ['nis' => '5968', 'name' => 'FATIANSA PUTRI PRASETYO', 'class' => 'XG'],
            ['nis' => '5994', 'name' => 'GENDIS PUTRI SEKAR ARUM', 'class' => 'XG'],
            ['nis' => '6025', 'name' => 'JULIO GILANG KUSUMA NUGRAHA', 'class' => 'XG'],
            ['nis' => '6033', 'name' => 'KINTAN NUR KHASANAH', 'class' => 'XG'],
            ['nis' => '6034', 'name' => 'LAKEISYA SYIFA AZARIA', 'class' => 'XG'],
            ['nis' => '6055', 'name' => 'LUTFIA RAHMATTULAILA RUSADY', 'class' => 'XG'],
            ['nis' => '6070', 'name' => 'MIFTHAKHUL HANUM VIRGANI', 'class' => 'XG'],
            ['nis' => '6076', 'name' => 'MUHAMMAD RASYA AL FATIN ISTAQRI', 'class' => 'XG'],
            ['nis' => '6082', 'name' => 'NAILA FIRDA AMALIA', 'class' => 'XG'],
            ['nis' => '6089', 'name' => 'NASYA AULYA NUR ROHMAH', 'class' => 'XG'],
            ['nis' => '6094', 'name' => 'NAUFAL EVAN FIRZATULLAH', 'class' => 'XG'],
            ['nis' => '6096', 'name' => 'NAURA PUTRI RAHMADHANI', 'class' => 'XG'],
            ['nis' => '6100', 'name' => 'NIDA FARADISA YURIANTO', 'class' => 'XG'],
            ['nis' => '6101', 'name' => 'NI\'MA JOELANK NASHIR', 'class' => 'XG'],
            ['nis' => '6118', 'name' => 'PARAMUDITA TYAS MAHARANI', 'class' => 'XG'],
            ['nis' => '6163', 'name' => 'SALSABILLAH PRABAWATI', 'class' => 'XG'],
            ['nis' => '5954', 'name' => 'SATRIA PARAMA ABHINAYA', 'class' => 'XG'],
            ['nis' => '5931', 'name' => 'SEPA GATAN PUTRA SETIAWAN', 'class' => 'XG'],
            ['nis' => '5991', 'name' => 'SYAFA AULIA', 'class' => 'XG'],
            ['nis' => '6016', 'name' => 'THERESIA CITRA ARTY AMAVISTA PANDU', 'class' => 'XG'],
            ['nis' => '6143', 'name' => 'ZAHRA ISNAINI NURKHASANAH', 'class' => 'XG'],
            ['nis' => '6159', 'name' => 'ZIVANNA NEYZA SAFRIAN', 'class' => 'XG'],
        ];

        foreach ($students as $data) {
            $user = User::firstOrCreate(
                ['email' => $data['nis'] . '@duplay.com'], 
                [
                    'name'     => $data['name'],
                    'password' => Hash::make('duplay123'),
                    'role'     => 'siswa',
                ]
            );

            Student::firstOrCreate(
                ['nis' => $data['nis']], 
                [
                    'user_id' => $user->id,
                    'name'    => $data['name'],
                    'class'   => $data['class'],
                ]
            );
        }
    }
}
